{{- if  (eq .Values.global.env "prod") }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}-api-{{ .Values.global.env }}
  labels:
    app: {{ .Chart.Name }}-api-{{ .Values.global.env }}
spec:
  replicas: 1
  selector:
      matchLabels:
        app: {{ .Chart.Name }}-api-{{ .Values.global.env }}
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}-api-{{ .Values.global.env }}
    spec:
      containers:
      - name: {{ .Chart.Name }}-api-{{ .Values.global.env }}
        env:
        - name: SECRET
          valueFrom:
            configMapKeyRef:
              name: {{ .Chart.Name }}-common-config
              key: secret
{{ tuple "billing-proxy-api-prod" . | include "werf_container_image" | indent 8 }}
      volumes:
      - name: config-files
        configMap:
          name: {{ .Chart.Name }}-common-config

---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}-service-api
  labels:
    app: {{ .Chart.Name }}-service-api
spec:
  clusterIP: None
  selector:
    app: {{ .Chart.Name }}-api-{{ .Values.global.env }}
  ports:
  - name: {{ .Chart.Name }}-api-{{ .Values.global.env }}
    port: 80
    protocol: TCP

{{- else }}

{{- end }}
